### ISSUE TITLE
Fix contribuitors graph

### ISSUE THREAD

**Issue by jhon-p16** [FunPythonEC/Hacktoberfest-GYE-2022#7]
https://github.com/FunPythonEC/Hacktoberfest-GYE-2022/blob/d5863f5c2546ca95fc75ea2907fd61adcfb0c507/README.md?plain=1#L84

**Comment by whacosta** [comment]
Parece ser que ya esta solucionado xD

**Comment by jhon-p16** [comment]
tienes razon, ya se actulizo'
